# Generated by Django 5.0.1 on 2024-02-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_extract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
    ]
