# Generated by Django 5.0.1 on 2024-02-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_extract', '0002_validatedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('emails', models.ManyToManyField(related_name='bulk_email_lists', to='email_extract.validatedemail')),
            ],
        ),
    ]
